class_name SkillLibraryWeapon
extends RefCounted

## 六武器主動技,每武器 9 階(F~SSS)各一個,捕夢網 E 階額外保留既有的治癒/降咒兩支
## (合併進安寢術之前的獨立效果,見下方「捕夢網」區塊說明)。階級只代表訓練抽選時的
## 稀有度/取得難度,同一武器內的倍率刻意壓在同一區間,靠範圍形狀/機制分工,不是線性堆疊
## (見技能總冊網站的設計哲學)。
##
## 命名慣例:每個武器對應一個具名 attack 入口(SkillEffectLibrary.sword_attack() 等),
## 純攻擊技直接綁那個入口;複合效果(攻擊+素質減益、攻擊+機制)綁
## weapon_attack_with_stat_debuff()/weapon_attack_with_mechanic(),用 Callable.bind()
## 把武器種類(以及減益素質/幅度)固定進去,不用為每個複合技各寫一個專屬效果函式。

static func build() -> Array[Skill]:
	var library: Array[Skill] = []
	library.append_array(_sword_skills())
	library.append_array(_bow_skills())
	library.append_array(_shield_skills())
	library.append_array(_dagger_skills())
	library.append_array(_staff_skills())
	library.append_array(_dream_skills())
	return library


static func _sword_skills() -> Array[Skill]:
	var skills: Array[Skill] = []

	skills.append(SkillBuilder.new()
		.name("削擊")
		.description("剛學會用劍的基礎揮砍,招式雖生澀,卻一板一眼地直來直往,無從閃躲")
		.rank(GameEnums.RankType.F)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(40.0).skill_ratio(2.6).true_hit()
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("熟練斬")
		.description("反覆鍛鍊出的橫掃步法,劍鋒掃過眼前一整排的敵人")
		.rank(GameEnums.RankType.E)
		.skill_range(1).area_shape(GameEnums.AreaShape.LINE).area_size(2)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(36.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("破甲斬")
		.description("瞄準鎧甲縫隙劈砍,傷害普通但直接無視防禦")
		.rank(GameEnums.RankType.D)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(34.0).skill_ratio(2.6)
		.mechanics([GameEnums.SkillMechanic.ARMOR_PIERCE])
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("連環斬")
		.description("手腕翻轉補上第二刀,兩次判定各自吃迴避與暴擊")
		.rank(GameEnums.RankType.C)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(36.0).skill_ratio(2.2).multi_strike(2)
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("旋風斬")
		.description("原地旋身橫掃,劍鋒掃過周圍所有敵人,單挑不划算")
		.rank(GameEnums.RankType.B)
		.skill_range(1).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(33.0).skill_ratio(2.0)
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("怒濤斬擊")
		.description("蓄力後全力揮出,力道扎實但破綻也大")
		.rank(GameEnums.RankType.A)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(28.0).skill_ratio(3.4)
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("弒神一擊")
		.description("捨棄防禦全力突進,賭上一切換取致命一劍")
		.rank(GameEnums.RankType.S)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(24.0).skill_ratio(3.8)
		.mechanics([GameEnums.SkillMechanic.ARMOR_PIERCE])
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("熾焰橫斬")
		.description("劍身高速揮動迸發熱能衝擊,直接重創目標")
		.rank(GameEnums.RankType.SS)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(36.0).skill_ratio(2.8)
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("劍聖・天崩地裂")
		.description("集畢生劍術於一擊,劍氣席捲戰場,單體效率反不如基礎劍招")
		.rank(GameEnums.RankType.SSS)
		.skill_range(1).area_shape(GameEnums.AreaShape.RADIUS).area_size(3)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SWORD)
		.base_chance(26.0).skill_ratio(2.4)
		.action(Callable(SkillEffectLibrary, "sword_attack"))
		.build())

	return skills


static func _bow_skills() -> Array[Skill]:
	var skills: Array[Skill] = []

	skills.append(SkillBuilder.new()
		.name("疾射")
		.description("迅速搭箭放出的一箭,速度快、命中率高")
		.rank(GameEnums.RankType.F)
		.skill_range(4).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(42.0).skill_ratio(2.8)
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("疾風箭") # 既有(原「精準射擊」),改為直線 2 格
		.description("小幅度扇形連射,一次掠過眼前直線 2 格內的敵人")
		.rank(GameEnums.RankType.E)
		.skill_range(4).area_shape(GameEnums.AreaShape.LINE).area_size(2)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(36.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("連珠箭")
		.description("連續搭箭疾射,拆成兩箭各自判定")
		.rank(GameEnums.RankType.D)
		.skill_range(4).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(38.0).skill_ratio(2.4).multi_strike(2)
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("穿心箭")
		.description("瞄準要害貫穿而出,傷害高但破綻也大")
		.rank(GameEnums.RankType.C)
		.skill_range(4).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(26.0).skill_ratio(3.4)
		.mechanics([GameEnums.SkillMechanic.ARMOR_PIERCE])
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("貫穿射線")
		.description("拉弓射出重箭,貫穿一整條直線上的敵人")
		.rank(GameEnums.RankType.B)
		.skill_range(4).area_shape(GameEnums.AreaShape.LINE).area_size(3)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(32.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("獵鷹之眼")
		.description("鎖定要害全力一射,巧勁勝過蠻力")
		.rank(GameEnums.RankType.A)
		.skill_range(4).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(40.0).skill_ratio(3.0)
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("落日連射")
		.description("短時間連續放箭形成箭幕,覆蓋整個方向")
		.rank(GameEnums.RankType.S)
		.skill_range(4).area_shape(GameEnums.AreaShape.LINE).area_size(4)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(34.0).skill_ratio(2.0)
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("破空箭")
		.description("蓄滿全力的一箭,箭速快到肉眼難以捕捉")
		.rank(GameEnums.RankType.SS)
		.skill_range(5).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(24.0).skill_ratio(3.6)
		.mechanics([GameEnums.SkillMechanic.GUARANTEED_CRIT])
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("千羽落星")
		.description("漫天箭雨如流星墜落,籠罩範圍但單體不算突出")
		.rank(GameEnums.RankType.SSS)
		.skill_range(4).area_shape(GameEnums.AreaShape.RADIUS).area_size(3)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.BOW)
		.base_chance(28.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "bow_attack"))
		.build())

	return skills


static func _shield_skills() -> Array[Skill]:
	var skills: Array[Skill] = []

	skills.append(SkillBuilder.new()
		.name("盾擊")
		.description("以盾牌邊角輕擊敵人,近身貼臉的距離讓對手無從閃避")
		.rank(GameEnums.RankType.F)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(40.0).skill_ratio(2.4).true_hit()
		.action(Callable(SkillEffectLibrary, "shield_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("破盾衝撞") # 既有(原「盾牌重擊」,原屬 D 階)
		.description("舉盾全力衝撞,撞開敵人的防線")
		.rank(GameEnums.RankType.E)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(36.0).skill_ratio(2.6)
		.mechanics([GameEnums.SkillMechanic.ARMOR_PIERCE])
		.action(Callable(SkillEffectLibrary, "shield_attack"))
		.build())

	## 群體嘲諷:設計表上原本標成「自身/範圍」的防禦類型,但嘲諷的對象是敵人,要走
	## DEBUFF 型別才會從 caster.enemies 挑目標(見 Skill._candidate_pool()),這裡改成
	## 鎖定一個敵人、以其為中心的範圍嘲諷,而不是無視距離的全體技。
	skills.append(SkillBuilder.new()
		.name("群體嘲諷")
		.description("重重敲擊盾面,將範圍內敵人的注意力全數引向自己")
		.rank(GameEnums.RankType.D)
		.skill_range(2).area_shape(GameEnums.AreaShape.RADIUS).area_size(3)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.DEBUFF)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(30.0).skill_ratio(0.0).duration_rounds(2)
		.mechanics([GameEnums.SkillMechanic.TAUNT])
		.action(Callable(SkillEffectLibrary, "targeted_mechanic_debuff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("鋼鐵壁壘")
		.description("就地舉盾嚴陣以待,為自己張開一層能吸收傷害的護盾")
		.rank(GameEnums.RankType.C)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.SHIELD)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(30.0).skill_ratio(1.2).duration_rounds(2)
		.action(Callable(SkillEffectLibrary, "shield"))
		.build())

	skills.append(SkillBuilder.new()
		.name("守護聖盾")
		.description("挺身而出,為周圍隊友張開能吸收傷害的護盾")
		.rank(GameEnums.RankType.B)
		.skill_range(0).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.SHIELD)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(28.0).skill_ratio(0.9).duration_rounds(2)
		.action(Callable(SkillEffectLibrary, "shield"))
		.build())

	skills.append(SkillBuilder.new()
		.name("震地擊")
		.description("盾牌重重砸向地面,震波撼動周遭敵人")
		.rank(GameEnums.RankType.A)
		.skill_range(1).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(32.0).skill_ratio(2.0)
		.action(Callable(SkillEffectLibrary, "shield_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("不屈壁壘")
		.description("全隊士氣振奮,人人張開一層能吸收傷害的護盾")
		.rank(GameEnums.RankType.S)
		.skill_range(0).area_shape(GameEnums.AreaShape.ALL_ALLIES).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.SHIELD)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(30.0).skill_ratio(0.7).duration_rounds(1)
		.action(Callable(SkillEffectLibrary, "shield"))
		.build())

	skills.append(SkillBuilder.new()
		.name("聖盾反擊")
		.description("盾牌重重一撞,命中後強迫對方盯上自己")
		.rank(GameEnums.RankType.SS)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(34.0).skill_ratio(2.6).duration_rounds(1)
		.mechanics([GameEnums.SkillMechanic.TAUNT])
		.action(Callable(SkillEffectLibrary, "weapon_attack_with_mechanic").bind(GameEnums.WeaponType.SHIELD))
		.build())

	skills.append(SkillBuilder.new()
		.name("泰坦壁壘")
		.description("化身無法撼動的巨盾堡壘,為全軍張開堅實的護盾")
		.rank(GameEnums.RankType.SSS)
		.skill_range(0).area_shape(GameEnums.AreaShape.ALL_ALLIES).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.SHIELD)
		.bind_weapon(GameEnums.WeaponType.SHIELD)
		.base_chance(32.0).skill_ratio(0.9).duration_rounds(2)
		.action(Callable(SkillEffectLibrary, "shield"))
		.build())

	return skills


static func _dagger_skills() -> Array[Skill]:
	var skills: Array[Skill] = []

	skills.append(SkillBuilder.new()
		.name("刺擊")
		.description("貼近敵人身側快速一刺,欺近死角讓對手來不及反應")
		.rank(GameEnums.RankType.F)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(44.0).skill_ratio(2.8).true_hit()
		.action(Callable(SkillEffectLibrary, "dagger_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("絕影突刺") # 既有(原「影襲」),改為攻擊+削弱敏捷的複合技
		.description("欺近敵人身側劃開要害,順勢削弱其反應速度")
		.rank(GameEnums.RankType.E)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(36.0).skill_ratio(2.4).duration_rounds(1)
		.action(Callable(SkillEffectLibrary, "weapon_attack_with_stat_debuff").bind(
			GameEnums.WeaponType.DAGGER, [GameEnums.PotentialType.AGILITY] as Array[int], -0.15
		))
		.build())

	skills.append(SkillBuilder.new()
		.name("蝶舞連刺")
		.description("身形如蝶般連續閃動,拆成兩刺各自判定")
		.rank(GameEnums.RankType.D)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(38.0).skill_ratio(2.2).multi_strike(2)
		.action(Callable(SkillEffectLibrary, "dagger_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("割裂腱")
		.description("精準割向敵人腿部肌腱,使其行動遲緩")
		.rank(GameEnums.RankType.C)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.DEBUFF)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(32.0).skill_ratio(-0.2).duration_rounds(2)
		.buffed_stats([GameEnums.PotentialType.AGILITY])
		.action(Callable(SkillEffectLibrary, "stat_debuff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("瞬影突刺")
		.description("瞬間欺身欺近死角,狠狠刺穿對手的破綻")
		.rank(GameEnums.RankType.B)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(34.0).skill_ratio(3.2)
		.action(Callable(SkillEffectLibrary, "dagger_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("血月連斬")
		.description("如血月般狂舞的連續突刺,三刺各自判定")
		.rank(GameEnums.RankType.A)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(40.0).skill_ratio(2.0).multi_strike(3)
		.action(Callable(SkillEffectLibrary, "dagger_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("暗影分身")
		.description("殘影般的快速位移連續突襲,敵人難辨真身")
		.rank(GameEnums.RankType.S)
		.skill_range(1).area_shape(GameEnums.AreaShape.LINE).area_size(2)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(32.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "dagger_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("絕命一擊")
		.description("抓準對手破綻,毫不留情送出致命一刀")
		.rank(GameEnums.RankType.SS)
		.skill_range(1).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(22.0).skill_ratio(3.6)
		.mechanics([GameEnums.SkillMechanic.GUARANTEED_CRIT])
		.action(Callable(SkillEffectLibrary, "dagger_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("千刃夜舞")
		.description("化身夜色中的千萬道刀影,範圍雖廣但單體偏弱")
		.rank(GameEnums.RankType.SSS)
		.skill_range(1).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DAGGER)
		.base_chance(28.0).skill_ratio(2.0)
		.mechanics([GameEnums.SkillMechanic.ARMOR_PIERCE])
		.action(Callable(SkillEffectLibrary, "dagger_attack"))
		.build())

	return skills


static func _staff_skills() -> Array[Skill]:
	var skills: Array[Skill] = []

	skills.append(SkillBuilder.new()
		.name("星火術")
		.description("凝聚微弱火花射向敵人,魔力尚淺卻紮實可靠")
		.rank(GameEnums.RankType.F)
		.skill_range(3).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(38.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "staff_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("爆炎術") # 既有(原「火球術」)
		.description("引燃魔力凝成的火焰彈,炸開波及周遭敵人")
		.rank(GameEnums.RankType.E)
		.skill_range(3).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(26.0).skill_ratio(2.0)
		.action(Callable(SkillEffectLibrary, "staff_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("寒冰箭")
		.description("凝結寒氣射出冰箭,刺骨寒意同時拖慢對手腳步")
		.rank(GameEnums.RankType.D)
		.skill_range(3).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(32.0).skill_ratio(2.2).duration_rounds(2)
		.action(Callable(SkillEffectLibrary, "weapon_attack_with_stat_debuff").bind(
			GameEnums.WeaponType.STAFF, [GameEnums.PotentialType.AGILITY] as Array[int], -0.15
		))
		.build())

	skills.append(SkillBuilder.new()
		.name("詛咒雷擊")
		.description("召喚帶著詛咒的雷霆劈向指定區域,受創的敵人傷口難以被治癒")
		.rank(GameEnums.RankType.C)
		.skill_range(3).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(30.0).skill_ratio(1.8).duration_rounds(2)
		.mechanics([GameEnums.SkillMechanic.HEAL_DOWN])
		.action(Callable(SkillEffectLibrary, "weapon_attack_with_mechanic").bind(GameEnums.WeaponType.STAFF))
		.build())

	skills.append(SkillBuilder.new()
		.name("減速力場")
		.description("展開扭曲時空的力場,拖慢範圍內敵人腳步")
		.rank(GameEnums.RankType.B)
		.skill_range(3).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.DEBUFF)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(28.0).skill_ratio(-0.2).duration_rounds(2)
		.buffed_stats([GameEnums.PotentialType.AGILITY])
		.action(Callable(SkillEffectLibrary, "stat_debuff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("爆裂新星")
		.description("引爆凝聚已久的魔力,以自身為中心炸裂四方")
		.rank(GameEnums.RankType.A)
		.skill_range(0).area_shape(GameEnums.AreaShape.RADIUS).area_size(3)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(30.0).skill_ratio(1.6)
		.action(Callable(SkillEffectLibrary, "staff_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("熾陽烈焰")
		.description("召喚灼熱火柱貫穿戰場,直接重創路徑上的敵人")
		.rank(GameEnums.RankType.S)
		.skill_range(3).area_shape(GameEnums.AreaShape.LINE).area_size(3)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(32.0).skill_ratio(1.8)
		.action(Callable(SkillEffectLibrary, "staff_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("隕石墜擊")
		.description("呼喚天外隕石重重砸落,炸出衝擊波")
		.rank(GameEnums.RankType.SS)
		.skill_range(4).area_shape(GameEnums.AreaShape.RADIUS).area_size(3)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(26.0).skill_ratio(2.0)
		.action(Callable(SkillEffectLibrary, "staff_attack"))
		.build())

	skills.append(SkillBuilder.new()
		.name("天啟審判")
		.description("撕裂天際降下魔法洪流,稀有難學但單體效率一般")
		.rank(GameEnums.RankType.SSS)
		.skill_range(4).area_shape(GameEnums.AreaShape.RADIUS).area_size(4)
		.effect_stat(GameEnums.PotentialType.INTELLIGENCE)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.STAFF)
		.base_chance(24.0).skill_ratio(1.6)
		.mechanics([GameEnums.SkillMechanic.ARMOR_PIERCE])
		.action(Callable(SkillEffectLibrary, "staff_attack"))
		.build())

	return skills


static func _dream_skills() -> Array[Skill]:
	var skills: Array[Skill] = []

	skills.append(SkillBuilder.new()
		.name("微光術")
		.description("捕夢網滲出淡淡微光,輕輕觸碰般地攻擊敵人")
		.rank(GameEnums.RankType.F)
		.skill_range(2).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(38.0).skill_ratio(2.4)
		.action(Callable(SkillEffectLibrary, "dreamcatcher_attack"))
		.build())

	## 既有的「聖光審判」「治癒」「降咒」三支 E 階技能,合併重做成單一複合技(治療+護盾),
	## 同一武器同一階級只保留一個技能,不並排多個選項互相比較。
	skills.append(SkillBuilder.new()
		.name("安寢術")
		.description("捕夢網編織安穩夢境,撫平隊友傷勢並張開一層薄薄的護盾")
		.rank(GameEnums.RankType.E)
		.skill_range(0).area_shape(GameEnums.AreaShape.RADIUS).area_size(3)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.HEAL)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(28.0).skill_ratio(2.2).duration_rounds(2)
		.action(Callable(SkillEffectLibrary, "heal_with_shield"))
		.build())

	skills.append(SkillBuilder.new()
		.name("夢魘低語")
		.description("以夢囈般的低語擾亂敵人心神,偶爾使其心生恐懼")
		.rank(GameEnums.RankType.D)
		.skill_range(2).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(32.0).skill_ratio(2.6).duration_rounds(1)
		.mechanics([GameEnums.SkillMechanic.FEAR])
		.action(Callable(SkillEffectLibrary, "weapon_attack_with_mechanic").bind(GameEnums.WeaponType.DREAMCATCHER))
		.build())

	skills.append(SkillBuilder.new()
		.name("心靈屏障")
		.description("捕夢網編織柔韌的心靈結界,為全隊張開一層能吸收傷害的護盾")
		.rank(GameEnums.RankType.C)
		.skill_range(0).area_shape(GameEnums.AreaShape.ALL_ALLIES).area_size(1)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.SHIELD)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(30.0).skill_ratio(0.8).duration_rounds(2)
		.action(Callable(SkillEffectLibrary, "shield"))
		.build())

	skills.append(SkillBuilder.new()
		.name("群體庇護")
		.description("捕夢網展開柔和光罩,守護周遭隊友")
		.rank(GameEnums.RankType.B)
		.skill_range(0).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.HEAL)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(30.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "heal"))
		.build())

	skills.append(SkillBuilder.new()
		.name("淨化之光")
		.description("聖潔光輝洗去傷勢,偶爾一併洗去一項異常狀態")
		.rank(GameEnums.RankType.A)
		.skill_range(2).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.HEAL)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(32.0).skill_ratio(3.0)
		.action(Callable(SkillEffectLibrary, "heal_with_cleanse"))
		.build())

	skills.append(SkillBuilder.new()
		.name("群夢侵蝕")
		.description("深沉惡夢瀰漫敵陣,範圍內敵人同時陷入恐懼")
		.rank(GameEnums.RankType.S)
		.skill_range(2).area_shape(GameEnums.AreaShape.RADIUS).area_size(2)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(28.0).skill_ratio(2.4).duration_rounds(1)
		.mechanics([GameEnums.SkillMechanic.FEAR])
		.action(Callable(SkillEffectLibrary, "weapon_attack_with_mechanic").bind(GameEnums.WeaponType.DREAMCATCHER))
		.build())

	skills.append(SkillBuilder.new()
		.name("聖域結界")
		.description("展開守護全隊的神聖結界,持續治癒每一位夥伴")
		.rank(GameEnums.RankType.SS)
		.skill_range(0).area_shape(GameEnums.AreaShape.ALL_ALLIES).area_size(1)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.HEAL)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(30.0).skill_ratio(1.8)
		.action(Callable(SkillEffectLibrary, "heal"))
		.build())

	skills.append(SkillBuilder.new()
		.name("夢境輪迴")
		.description("操控生死輪迴般的夢境之力,稀有難學,治癒之餘一併安撫心神")
		.rank(GameEnums.RankType.SSS)
		.skill_range(0).area_shape(GameEnums.AreaShape.ALL_ALLIES).area_size(1)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.HEAL)
		.bind_weapon(GameEnums.WeaponType.DREAMCATCHER)
		.base_chance(26.0).skill_ratio(2.2)
		.action(Callable(SkillEffectLibrary, "heal_with_cleanse"))
		.build())

	return skills
