class_name SkillLibraryPassive
extends RefCounted

## 通用被動,不綁定武器(GameEnums.NO_WEAPON_BINDING),9 階各 2 支(F~SSS)。多數是永久
## 素質加成(passive_stat_buff),少數是反應式/機率式的戰場行為,見各技能註解對應的
## SkillMechanic 與 SkillEffectLibrary 的 check_*()/maybe_*() 系列函式。
## 「迴避率提升」類設計簡化成 AGI 永久加成(閃避率本來就是 AGI 換算出來的,見
## CombatResolver.judge_dodge()),不另外開一個獨立的迴避率修正欄位。

static func build() -> Array[Skill]:
	var skills: Array[Skill] = []

	skills.append(SkillBuilder.new()
		.name("新兵鬥志")
		.description("剛踏上戰場的鬥氣,小幅提升力量與敏捷")
		.rank(GameEnums.RankType.F)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.08)
		.buffed_stats([GameEnums.PotentialType.STRENGTH, GameEnums.PotentialType.AGILITY])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("未雨綢繆") 
		.description("行伍間養成的警覺,小幅提升敏捷與智慧")
		.rank(GameEnums.RankType.F)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.06)
		.buffed_stats([GameEnums.PotentialType.AGILITY, GameEnums.PotentialType.INTELLIGENCE])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("文武雙修") # 既有,效果不變
		.description("自幼兼修武藝與謀略,永久提升力量與智慧")
		.rank(GameEnums.RankType.E)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.12)
		.buffed_stats([GameEnums.PotentialType.STRENGTH, GameEnums.PotentialType.INTELLIGENCE])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("泰然自若")
		.description("面對紛亂戰局仍不動如山,對控制類異常狀態有較高抵抗")
		.rank(GameEnums.RankType.E)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.MENTALITY)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(40.0)
		.action(Callable(SkillEffectLibrary, "passive_status_resist_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("迅捷步伐")
		.description("長年征戰練就的靈巧身手,提升敏捷與靈巧")
		.rank(GameEnums.RankType.D)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.10)
		.buffed_stats([GameEnums.PotentialType.AGILITY, GameEnums.PotentialType.DEXTERITY])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("戰鬥直覺")
		.description("剛閃過攻擊的瞬間最是清醒,迴避成功後一定機率立即反擊攻擊者")
		.rank(GameEnums.RankType.D)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.DEFEND)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(30.0).skill_ratio(0.0)
		.mechanics([GameEnums.SkillMechanic.DODGE_COUNTER])
		.action(Callable(SkillEffectLibrary, "reactive_passive_noop"))
		.build())

	skills.append(SkillBuilder.new()
		.name("不屈之軀")
		.description("千錘百鍊的軀體,提升活力與力量")
		.rank(GameEnums.RankType.C)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.10)
		.buffed_stats([GameEnums.PotentialType.VITALITY, GameEnums.PotentialType.STRENGTH])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("乘勝追擊")
		.description("擊殺敵人後士氣大振,本回合內下次行動技能權重提升")
		.rank(GameEnums.RankType.C)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.30).duration_rounds(1)
		.mechanics([GameEnums.SkillMechanic.KILL_MOMENTUM])
		.action(Callable(SkillEffectLibrary, "reactive_passive_noop"))
		.build())

	skills.append(SkillBuilder.new()
		.name("戰場直覺")
		.description("對危險與破綻異常敏銳,提升敏捷與精神")
		.rank(GameEnums.RankType.B)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.AGILITY)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.12)
		.buffed_stats([GameEnums.PotentialType.AGILITY, GameEnums.PotentialType.MENTALITY])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("破綻洞察")
		.description("總能一眼看穿防禦的空隙,攻擊有小機率無視防禦")
		.rank(GameEnums.RankType.B)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(15.0).skill_ratio(0.0)
		.mechanics([GameEnums.SkillMechanic.CHANCE_ARMOR_PIERCE])
		.action(Callable(SkillEffectLibrary, "reactive_passive_noop"))
		.build())

	skills.append(SkillBuilder.new()
		.name("劍膽琴心")
		.description("剛柔並濟的修為,提升力量與智慧")
		.rank(GameEnums.RankType.A)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.12)
		.buffed_stats([GameEnums.PotentialType.STRENGTH, GameEnums.PotentialType.INTELLIGENCE])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("絕境求生")
		.description("逼到絕境反而冷靜,HP 低於 30% 時受到傷害降低")
		.rank(GameEnums.RankType.A)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.DEFEND)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.20).hp_threshold(0.3)
		.mechanics([GameEnums.SkillMechanic.DAMAGE_REDUCTION])
		.action(Callable(SkillEffectLibrary, "reactive_passive_noop"))
		.build())

	skills.append(SkillBuilder.new()
		.name("一騎當千")
		.description("獨當一面的絕世武藝,提升力量與敏捷")
		.rank(GameEnums.RankType.S)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.14)
		.buffed_stats([GameEnums.PotentialType.STRENGTH, GameEnums.PotentialType.AGILITY])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("身經百戰")
		.description("久經沙場淬鍊出的鋼鐵般肉身,永久小幅降低所受傷害")
		.rank(GameEnums.RankType.S)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.VITALITY)
		.skill_type(GameEnums.SkillType.DEFEND)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.10).hp_threshold(0.0)
		.mechanics([GameEnums.SkillMechanic.DAMAGE_REDUCTION])
		.action(Callable(SkillEffectLibrary, "reactive_passive_noop"))
		.build())

	skills.append(SkillBuilder.new()
		.name("戰神附體")
		.description("彷彿戰神親臨的氣勢,提升力量與活力")
		.rank(GameEnums.RankType.SS)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.14)
		.buffed_stats([GameEnums.PotentialType.STRENGTH, GameEnums.PotentialType.VITALITY])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("絕殺直覺")
		.description("總能抓到那個瞬間,攻擊有小機率必定暴擊")
		.rank(GameEnums.RankType.SS)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.DEXTERITY)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(12.0).skill_ratio(0.0)
		.mechanics([GameEnums.SkillMechanic.CHANCE_GUARANTEED_CRIT])
		.action(Callable(SkillEffectLibrary, "reactive_passive_noop"))
		.build())

	skills.append(SkillBuilder.new()
		.name("超凡入聖")
		.description("超脫凡人極限,同時小幅提升全部六項素質")
		.rank(GameEnums.RankType.SSS)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.BUFF)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(0.08)
		.buffed_stats([
			GameEnums.PotentialType.STRENGTH, GameEnums.PotentialType.VITALITY,
			GameEnums.PotentialType.AGILITY, GameEnums.PotentialType.DEXTERITY,
			GameEnums.PotentialType.INTELLIGENCE, GameEnums.PotentialType.MENTALITY,
		])
		.action(Callable(SkillEffectLibrary, "passive_stat_buff"))
		.build())

	skills.append(SkillBuilder.new()
		.name("怒濤反擊")
		.description("每場戰鬥限一次,HP 低於 20% 時下一次受擊自動觸發強力反擊")
		.rank(GameEnums.RankType.SSS)
		.skill_range(0).area_shape(GameEnums.AreaShape.SINGLE).area_size(1)
		.effect_stat(GameEnums.PotentialType.STRENGTH)
		.skill_type(GameEnums.SkillType.ATTACK)
		.bind_weapon(GameEnums.NO_WEAPON_BINDING)
		.passive().base_chance(0.0).skill_ratio(3.0).hp_threshold(0.2)
		.mechanics([GameEnums.SkillMechanic.LIMITED_EXECUTE_COUNTER])
		.action(Callable(SkillEffectLibrary, "reactive_passive_noop"))
		.build())

	return skills
